# Generated by Django 6.0.3 on 2026-03-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_admission_number'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.vehicleroute'),
        ),
    ]
