# Generated by Django 6.0.3 on 2026-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_aadhar_number_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_login_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
