# Generated by Django 6.0.3 on 2026-04-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_academicnotice_studentattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Fees'},
        ),
        migrations.AddField(
            model_name='fee',
            name='concession_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount/Concession given', max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='concession_remarks',
            field=models.TextField(blank=True, help_text='Reason for concession', null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_month',
            field=models.CharField(blank=True, choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], help_text='Month for which fee is being paid', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='previous_due_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Previous unpaid fee balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Check number or transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='due_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
