# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_fee_options_fee_concession_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_cash', models.BooleanField(default=True)),
                ('allow_cheque', models.BooleanField(default=True)),
                ('allow_card', models.BooleanField(default=False)),
                ('allow_online_transfer', models.BooleanField(default=False)),
                ('allow_upi', models.BooleanField(default=False)),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_terms_note', models.CharField(blank=True, default='', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Option Setting',
                'verbose_name_plural': 'Payment Option Settings',
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(choices=[('superadmin', 'Super Admin'), ('principal', 'Principal'), ('viceprincipal', 'Vice Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('reception', 'Reception'), ('staff', 'Staff Admin')], max_length=30, unique=True)),
                ('can_access_students', models.BooleanField(default=False)),
                ('can_access_fee', models.BooleanField(default=False)),
                ('can_access_attendance', models.BooleanField(default=False)),
                ('can_access_academic', models.BooleanField(default=False)),
                ('can_access_staff', models.BooleanField(default=False)),
                ('can_access_exam', models.BooleanField(default=False)),
                ('can_access_transport', models.BooleanField(default=False)),
                ('can_access_settings', models.BooleanField(default=False)),
                ('can_access_reports', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Module Permission',
                'verbose_name_plural': 'Role Module Permissions',
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='RLCS School', max_length=150)),
                ('school_code', models.CharField(blank=True, default='', max_length=40)),
                ('principal_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('academic_year_label', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemOptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_open', models.BooleanField(default=True)),
                ('fee_receipt_auto_number', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('allow_student_portal', models.BooleanField(default=True)),
                ('require_transport_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Option Setting',
                'verbose_name_plural': 'System Option Settings',
            },
        ),
    ]
