# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_paymentoptionsetting_rolemodulepermission_schoolsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='receipt_prefix',
            field=models.CharField(blank=True, default='RCPT', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Thank you for your payment', max_length=250),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='show_logo_on_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='show_school_name_on_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='settings/logo/'),
        ),
    ]
