# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_schoolsetting_logo_and_receipt_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, default='Meta WhatsApp Cloud API', max_length=60)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=100)),
                ('business_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('webhook_verify_token', models.CharField(blank=True, default='', max_length=120)),
                ('instance_id', models.CharField(blank=True, default='', max_length=100)),
                ('default_country_code', models.CharField(blank=True, default='+91', max_length=8)),
                ('fee_receipt_template', models.CharField(blank=True, default='fee_receipt_notice', max_length=100)),
                ('due_fee_template', models.CharField(blank=True, default='due_fee_alert', max_length=100)),
                ('attendance_template', models.CharField(blank=True, default='attendance_alert', max_length=100)),
                ('enable_admission_alerts', models.BooleanField(default=False)),
                ('enable_fee_receipt_alerts', models.BooleanField(default=False)),
                ('enable_attendance_alerts', models.BooleanField(default=False)),
                ('enable_due_fee_alerts', models.BooleanField(default=False)),
                ('enable_result_alerts', models.BooleanField(default=False)),
                ('enable_general_broadcasts', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp API Setting',
                'verbose_name_plural': 'WhatsApp API Settings',
            },
        ),
    ]