# Generated by Django 6.0.3 on 2026-04-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_whatsappapisetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, default='', max_length=120)),
                ('mother_name', models.CharField(blank=True, default='', max_length=120)),
                ('husband_name', models.CharField(blank=True, default='', max_length=120)),
                ('qualification', models.CharField(blank=True, default='', max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='staff/photos/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('experience', models.CharField(blank=True, default='', max_length=120)),
                ('last_school_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='students.designation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['-id'],
            },
        ),
    ]