# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='login_password_plain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]