# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_staffprofile_login_password_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppControlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, default='RLCS School App', max_length=120)),
                ('android_latest_version', models.CharField(blank=True, default='1.0.0', max_length=20)),
                ('android_min_supported_version', models.CharField(blank=True, default='1.0.0', max_length=20)),
                ('force_update', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='Server maintenance in progress. Please try again later.', max_length=250)),
                ('student_app_enabled', models.BooleanField(default=True)),
                ('parent_app_enabled', models.BooleanField(default=True)),
                ('staff_app_enabled', models.BooleanField(default=True)),
                ('app_notice', models.CharField(blank=True, default='', max_length=250)),
                ('config_api_key', models.CharField(blank=True, default='', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile App Control Setting',
                'verbose_name_plural': 'Mobile App Control Settings',
            },
        ),
    ]