# Generated by Django 6.0.3 on 2026-04-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_mobileappcontrolsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappcontrolsetting',
            name='current_release_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mobileappcontrolsetting',
            name='parent_home_modules',
            field=models.TextField(blank=True, default='dashboard,attendance,fees,notices'),
        ),
        migrations.AddField(
            model_name='mobileappcontrolsetting',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mobileappcontrolsetting',
            name='staff_home_modules',
            field=models.TextField(blank=True, default='dashboard,attendance,academics,notices'),
        ),
        migrations.AddField(
            model_name='mobileappcontrolsetting',
            name='student_home_modules',
            field=models.TextField(blank=True, default='dashboard,attendance,fees,results,notices'),
        ),
        migrations.CreateModel(
            name='MobileAppDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(blank=True, default='', max_length=30)),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=300)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile App Device',
                'verbose_name_plural': 'Mobile App Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=30, unique=True)),
                ('version_code', models.PositiveIntegerField(default=1)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile App Release',
                'verbose_name_plural': 'Mobile App Releases',
                'ordering': ['-created_at'],
            },
        ),
    ]