# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_mobileappdevice_mobileapprelease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='half_yearly_fee_months',
            field=models.CharField(blank=True, default='apr,oct', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='once_fee_month',
            field=models.CharField(blank=True, default='apr', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='quarterly_fee_months',
            field=models.CharField(blank=True, default='apr,jul,oct,jan', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentoptionsetting',
            name='yearly_fee_month',
            field=models.CharField(blank=True, default='apr', max_length=10),
        ),
    ]