# Generated by Django 6.0.3 on 2026-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_timetableentry_homeworksetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('subject_name', models.CharField(max_length=120)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid Term'), ('final', 'Final Exam'), ('pre_board', 'Pre Board'), ('other', 'Other')], default='final', max_length=20)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.PositiveSmallIntegerField(default=100)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=200)),
                ('holiday_date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('state', 'State Holiday'), ('school', 'School Holiday'), ('examination', 'Examination Break'), ('other', 'Other')], default='school', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.CharField(default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=120)),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('unit_title', models.CharField(max_length=200)),
                ('topics', models.TextField()),
                ('teaching_hours', models.PositiveSmallIntegerField(default=1)),
                ('academic_year', models.CharField(default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_name', 'subject_name', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=120)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('full_year', 'Full Year')], default='full_year', max_length=20)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('class_name', 'section', 'subject_name', 'term')},
            },
        ),
    ]
