# Generated by Django 6.0.3 on 2026-03-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeamountslab',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feeparticular',
            name='amount',
        ),
        migrations.AddField(
            model_name='feeparticular',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('once', 'Once')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='FeeAmountSlabParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='fee.feeamountslab')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feeparticular')),
            ],
            options={
                'ordering': ['particular__name'],
                'unique_together': {('fee_slab', 'particular')},
            },
        ),
    ]
