# Generated by Django 6.0.3 on 2026-03-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_remove_feeamountslab_amount_and_more'),
        ('students', '0003_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feeparticular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='students.student')),
            ],
            options={
                'ordering': ['-applied_on'],
                'unique_together': {('student', 'particular')},
            },
        ),
    ]
