# Generated by Django 6.0.3 on 2026-03-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('other', 'Other')], default='bus', max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('conductor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('insurance_expiry', models.DateField()),
                ('permit_expiry', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, unique=True)),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_time', models.CharField(max_length=50)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stops', models.TextField(help_text='Comma-separated list of stops')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
            options={
                'ordering': ['route_name'],
            },
        ),
    ]
